#pragma once

void InitPrintPlayer();
void PrintDamageOnScreenHP(DWORD a, DWORD b, DWORD c, DWORD d, DWORD e);
void PrintDamageOnScreenSD(DWORD a, DWORD b, DWORD c, DWORD d, DWORD e);
void PrintPlayerMapName(char* a, char* b, char* c, char* d);
void PrintDrawCircleHPMP(DWORD a, float b, float c, float d, float e, float f, float g, float h, float i, int j, int k, GLfloat l);
void PrintDrawCircleSDBP(DWORD a, float b, float c, float d, float e, float f, float g, float h, float i, int j, int k, GLfloat l);
void PrintBarExperience1(float a, float b, float c, float d, float e, int f);
void PrintBarExperience2(float a, float b, DWORD c, float d, float e);
void PrintPlayerViewHP1(char* a, char* b);
void PrintPlayerViewHP2(float a, float b, DWORD c, float d, float e);
void PrintPlayerViewMP1(char* a, char* b);
void PrintPlayerViewMP2(float a, float b, DWORD c, float d, float e);
void PrintPlayerViewBP1(char* a, char* b);
void PrintPlayerViewBP2(float a, float b, DWORD c, float d, float e);
void PrintPlayerViewSD1(char* a, char* b);
void PrintPlayerViewSD2(float a, float b, DWORD c, float d, float e);
void PrintPlayerViewLevelUp(char* a, char* b);
void PrintPlayerViewStrength(char* a, char* b);
void PrintPlayerViewDexterity(char* a, char* b);
void PrintPlayerViewVitality(char* a, char* b);
void PrintPlayerViewEnergy(char* a, char* b);
void PrintPlayerViewLeadership(char* a, char* b);
void PrintPlayerViewAttackSpeed(char* a, char* b);
void PrintFixStatPoint();
void PrintPlayerSetAttackSpeed();

extern DWORD ViewIndex;
extern DWORD ViewLevel;
extern DWORD ViewReset;
extern DWORD ViewPoint;
extern DWORD ViewCurHP;
extern DWORD ViewMaxHP;
extern DWORD ViewCurMP;
extern DWORD ViewMaxMP;
extern DWORD ViewCurBP;
extern DWORD ViewMaxBP;
extern DWORD ViewCurSD;
extern DWORD ViewMaxSD;
extern DWORD ViewDamageHP;
extern DWORD ViewDamageSD;
extern DWORD ViewExperience;
extern DWORD ViewNextExperience;
extern DWORD ViewStrength;
extern DWORD ViewDexterity;
extern DWORD ViewVitality;
extern DWORD ViewEnergy;
extern DWORD ViewLeadership;
extern DWORD ViewAddStrength;
extern DWORD ViewAddDexterity;
extern DWORD ViewAddVitality;
extern DWORD ViewAddEnergy;
extern DWORD ViewAddLeadership;
extern DWORD ViewPhysiSpeed;
extern DWORD ViewMagicSpeed;